using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using System.Text;

public class StatsUpdate : MonoBehaviour {

	public Text score;
	public Text steps;
	public Text distance;

	// Use this for initialization
	void Start () {
		steps.text = PlayerPrefs.GetInt("currentSteps").ToString();
		score.text = PlayerPrefs.GetInt("totalPoints").ToString();
		distance.text = ((float)PlayerPrefs.GetInt("currentSteps")/2000.0f).ToString() + " mi.";
	}

	// Update is called once per frame
	void Update () {

	}
}
